version: '3.3'

networks:
  aw-network:
    driver: bridge

volumes:
  aw-mysql-volume:

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3306:3306"
    networks:
      - aw-network
    volumes:
      - aw-mysql-volume:/var/lib/mysql