server:
  port: 8085

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/aw_healthy_metric?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
  rabbitmq:
    password: rabbitmq
    host: localhost
    port: 5672
    username: rabbitmq
  cloud:
    stream:
      function:
        definition: healthCheckResultEventListener
      bindings:
        healthCheckResultEventListener-in-0:
          destination: health-check.v1.event.task-result
          group: metric
      rabbit:
        bindings:
          healthCheckResultEventListener-in-0:
            consumer:
              auto-bind-dlq: true